export type Block =
  | { type: 'p'; text: string }
  | { type: 'h2'; text: string }
  | { type: 'ul'; items: string[] };

export interface Localized {
  en: string;
  fr: string;
}

export interface BlogArticle {
  slug: string;
  title: Localized;
  excerpt: Localized;
  date: string;
  readTime: number;
  tag: Localized;
  content: { en: Block[]; fr: Block[] };
}

export const BLOG_ARTICLES: BlogArticle[] = [
  {
    slug: 'ai-receptionist-plumber-2026',
    title: {
      en: 'Why Every Plumber Needs an AI Receptionist in 2026',
      fr: "Pourquoi chaque plombier a besoin d'une réceptionniste IA en 2026",
    },
    excerpt: {
      en: 'Plumbing businesses miss up to 35% of inbound calls during service hours. An AI receptionist captures every lead, books appointments 24/7, and pays for itself within the first month.',
      fr: "Les entreprises de plomberie manquent jusqu'à 35 % des appels entrants pendant les heures de service. Une réceptionniste IA capture chaque prospect et prend les rendez-vous 24 h/24.",
    },
    date: '2026-04-10',
    readTime: 6,
    tag: { en: 'Home Services', fr: 'Services à domicile' },
    content: {
      en: [
        { type: 'p', text: "Every day, plumbing businesses across Europe and North America lose an estimated combined revenue in the billions because the phone rings out. That is not a marketing claim. On a thirty-minute gap between two service calls, a solo plumber can rack up eight missed calls, and every one of them dialed the next competitor before the truck even reached the driveway." },
        { type: 'p', text: "If you run a plumbing business, you have felt it. The client whose water heater flooded the basement at 11 p.m. Sunday who booked with someone else because your voicemail said we are closed. The commercial account that called Tuesday morning while you were under a sink and picked the next number on Google when the third ring went unanswered. The referred lead who called at 6 p.m. and heard a busy signal." },
        { type: 'p', text: "In 2026, an AI receptionist is not a gadget. It is the way to close the answer gap. Three shifts have made it inevitable: voice AI in French and English is now indistinguishable from a human on roughly 92 % of calls, the monthly cost has collapsed to 5–10 % of a full-time receptionist, and the plumbing shops that adopt it early are visibly outgrowing the ones that do not." },
        { type: 'h2', text: 'The three call moments plumbers still lose' },
        { type: 'p', text: "Field data from home-service benchmarks shows plumbing calls concentrate in three windows: 6–9 a.m. before the truck rolls, 12–2 p.m. around lunch and dispatch, and 5–10 p.m. after hours. A shop staffed only 9 to 5 catches the middle window at best. The morning and evening windows together account for around 41 % of inbound volume — and go straight to voicemail." },
        { type: 'p', text: "An AI receptionist runs on the same phone number twenty-four hours a day, in the caller's language. It never breaks for lunch. It never puts a client on hold to grab another line. It picks up on ring one, identifies the call type (emergency, quote, service, dispatch), captures the address, the issue and the callback window, then either books the appointment directly into your calendar or transfers the emergency to your on-call number." },
        { type: 'h2', text: 'What a single missed call actually costs' },
        { type: 'p', text: "The math is worth doing on paper. Average plumbing job in Belgium: around 280 €. Average lifetime value of a residential client who books two follow-up jobs plus one referral: around 1 100 €. If your close rate on inbound calls is 45 %, every missed call costs you 126 € in expected revenue, and roughly every fifth missed call costs a full 1 100 € in expected lifetime value." },
        { type: 'p', text: "Miss ten calls a week — a conservative number for a busy solo plumber — and the annual damage runs to around 65 000 € in lost revenue, plus the referral chain those clients would have started." },
        { type: 'h2', text: 'What the AI actually says on the call' },
        { type: 'p', text: "The best AI receptionists in 2026 do not sound robotic. They open with a natural greeting, ask three or four qualifying questions, then either book a slot or route the call. A typical script for a plumber looks like this:" },
        { type: 'ul', items: [
          'Greeting: name, business, offer to help',
          'Type triage: emergency, quote, existing job',
          'Address and city, with automatic postal-code capture',
          'Nature of the issue (leak, no hot water, blocked drain, etc.)',
          'Preferred window: today, tomorrow morning, this week',
          'Confirmation SMS with the booked slot and a photo-upload link',
        ]},
        { type: 'p', text: "The whole flow takes 90 to 150 seconds. The client hangs up with an appointment. You get a structured lead in your CRM with the transcript, the sentiment, and the address ready for routing." },
        { type: 'h2', text: 'Objections — and what is actually true' },
        { type: 'p', text: "My clients want a real human. In blind tests, 78 % of home-service callers cannot reliably tell a modern AI receptionist from a human when the voice quality is above a certain threshold. The remaining 22 % often report they prefer the AI because it does not put them on hold." },
        { type: 'p', text: "It will book garbage jobs. A well-configured AI qualifies harder than most human receptionists. It refuses out-of-zone requests, filters non-payer red-flag keywords, and can require a photo before confirming a large-quote job." },
        { type: 'p', text: "It is expensive. The going rate in 2026 for a bilingual AI receptionist covering a plumbing shop sits between 130 € and 400 € a month depending on volume, versus 2 300 € a month all-in for a part-time human." },
        { type: 'h2', text: 'Getting started — a realistic first month' },
        { type: 'p', text: "Day one: forward your business number to the AI, configure service zones, business hours, on-call number, service types and typical price ranges. Days two to seven: monitor every call and refine the qualifying script based on what you hear. Days eight to thirty: let the AI handle 100 % of inbound while you focus on the truck. Most plumbing shops recover the monthly cost within the first two booked emergency calls." },
        { type: 'p', text: "In 2026, missing a plumbing call is a choice. An AI receptionist is not a nice-to-have — it is the difference between growing and standing still." },
      ],
      fr: [
        { type: 'p', text: "Chaque jour, les entreprises de plomberie en Europe et en Amérique du Nord perdent collectivement des milliards de chiffre d'affaires parce que le téléphone sonne dans le vide. Ce n'est pas un slogan marketing. Sur trente minutes de battement entre deux interventions, un plombier solo peut cumuler huit appels manqués — et chacun d'entre eux a composé le concurrent suivant avant même que le camion n'atteigne l'allée." },
        { type: 'p', text: "Si vous gérez une entreprise de plomberie, vous connaissez la scène. Le client dont le chauffe-eau a inondé la cave dimanche à 23 h et qui a réservé ailleurs parce que votre répondeur disait « nous sommes fermés ». Le compte commercial qui a appelé mardi matin pendant que vous étiez sous un lavabo, et qui a cliqué sur le numéro suivant de Google quand la troisième sonnerie est restée sans réponse. Le prospect recommandé qui a téléphoné à 18 h et n'a eu que le signal occupé." },
        { type: 'p', text: "En 2026, une réceptionniste IA n'est pas un gadget. C'est la façon concrète de refermer le trou de couverture. Trois basculements l'ont rendue incontournable : la voix IA en français et en anglais est désormais indiscernable d'un humain sur environ 92 % des appels, le coût mensuel s'est effondré à 5–10 % d'une réceptionniste temps plein, et les plombiers qui adoptent tôt dépassent visiblement ceux qui restent immobiles." },
        { type: 'h2', text: 'Les trois moments où les plombiers perdent encore leurs appels' },
        { type: 'p', text: "Les données terrain des benchmarks de service à domicile montrent que les appels de plomberie se concentrent sur trois fenêtres : 6–9 h avant le départ du camion, 12–14 h autour de la pause et du dispatch, et 17–22 h en fin de journée. Un atelier ouvert 9–17 n'attrape au mieux que la fenêtre du milieu. Les fenêtres matin et soir représentent ensemble environ 41 % du volume entrant — et partent directement en messagerie." },
        { type: 'p', text: "Une réceptionniste IA vit sur le même numéro professionnel vingt-quatre heures sur vingt-quatre, dans la langue du client. Elle ne prend pas de pause. Elle ne met jamais un client en attente pour prendre une autre ligne. Elle décroche à la première sonnerie, identifie le type d'appel (urgence, devis, intervention, dispatch), capture l'adresse, la nature du problème et le créneau souhaité, puis pose le rendez-vous directement dans votre agenda ou transfère l'urgence à votre numéro d'astreinte." },
        { type: 'h2', text: "Le vrai coût d'un appel manqué" },
        { type: 'p', text: "Le calcul mérite d'être posé noir sur blanc. Ticket moyen d'un dépannage plomberie en Belgique : environ 280 €. Valeur à vie d'un client résidentiel qui repasse deux fois et recommande une fois : environ 1 100 €. Si votre taux de closing sur les appels entrants est de 45 %, chaque appel manqué vous coûte 126 € d'espérance de revenu, et à peu près un appel raté sur cinq vous coûte 1 100 € de valeur à vie perdue." },
        { type: 'p', text: "Manquez dix appels par semaine — un chiffre prudent pour un plombier solo chargé — et le dégât annuel dépasse 65 000 € de chiffre perdu, sans compter la chaîne de recommandations que ces clients auraient déclenchée." },
        { type: 'h2', text: "Ce que l'IA dit vraiment au téléphone" },
        { type: 'p', text: "Les meilleures réceptionnistes IA de 2026 ne sonnent pas mécaniques. Elles ouvrent avec un accueil naturel, posent trois ou quatre questions de qualification, puis soit posent le créneau, soit routent l'appel. Un script type pour un plombier ressemble à ceci :" },
        { type: 'ul', items: [
          'Accueil : nom, entreprise, proposition d\'aide',
          'Triage du type : urgence, devis, intervention en cours',
          'Adresse et ville, avec capture automatique du code postal',
          'Nature du problème (fuite, pas d\'eau chaude, canalisation bouchée, etc.)',
          'Créneau préféré : aujourd\'hui, demain matin, cette semaine',
          'SMS de confirmation avec le créneau réservé et un lien d\'envoi de photo',
        ]},
        { type: 'p', text: "L'ensemble prend 90 à 150 secondes. Le client raccroche avec un rendez-vous. Vous recevez un lead structuré dans votre CRM, avec la transcription, le score de sentiment et l'adresse prête pour le routage." },
        { type: 'h2', text: "Objections — et ce qui est réellement vrai" },
        { type: 'p', text: "Mes clients veulent parler à un vrai humain. En tests aveugles, 78 % des appelants de services à domicile ne distinguent pas de façon fiable une réceptionniste IA moderne d'un humain quand la qualité vocale dépasse un certain seuil. Les 22 % restants indiquent souvent préférer l'IA parce qu'elle ne les met pas en attente." },
        { type: 'p', text: "Elle va réserver n'importe quoi. Une IA bien configurée qualifie plus dur que la plupart des réceptionnistes humaines. Elle refuse les zones hors périmètre, filtre les mots-clés de mauvais payeur et peut exiger une photo avant de confirmer un gros devis." },
        { type: 'p', text: "C'est cher. Le tarif 2026 d'une réceptionniste IA bilingue pour un atelier de plomberie tourne entre 130 € et 400 € par mois selon le volume, contre 2 300 € par mois tout compris pour un temps partiel humain." },
        { type: 'h2', text: "Comment démarrer — un premier mois réaliste" },
        { type: 'p', text: "Jour 1 : renvoyez votre numéro professionnel vers l'IA, configurez les zones de service, les horaires, le numéro d'astreinte, les types d'intervention et vos fourchettes de prix. Jours 2 à 7 : écoutez chaque appel et ajustez le script de qualification en fonction de ce que vous entendez. Jours 8 à 30 : laissez l'IA prendre 100 % des appels entrants pendant que vous vous concentrez sur le terrain. La plupart des ateliers récupèrent le coût mensuel dès les deux premières urgences réservées." },
        { type: 'p', text: "En 2026, rater un appel de plomberie est un choix. Une réceptionniste IA n'est plus un confort — c'est la différence entre grandir et stagner." },
      ],
    },
  },

  {
    slug: 'dental-offices-ai-no-shows',
    title: {
      en: 'How Dental Offices Are Cutting No-Shows by 40% with AI',
      fr: "Comment les cabinets dentaires réduisent les absences de 40 % avec l'IA",
    },
    excerpt: {
      en: 'Automated confirmation calls, smart rescheduling and personalised reminders are transforming dental practice management and reclaiming thousands in lost revenue every month.',
      fr: 'Les appels de confirmation automatisés, la replanification intelligente et les rappels personnalisés transforment la gestion des cabinets dentaires et récupèrent des milliers d\'euros de revenus perdus.',
    },
    date: '2026-04-05',
    readTime: 7,
    tag: { en: 'Dental', fr: 'Dentaire' },
    content: {
      en: [
        { type: 'p', text: "In a typical general dentistry practice with two chairs, one no-show represents between 150 € and 400 € of chair time evaporated. Multiply that by the industry average — 12 to 18 % of scheduled appointments in Europe, 15 to 22 % in North America — and the annual leak reaches 80 000 to 140 000 € for a mid-size cabinet. It is not a small problem. It is the largest silent cost line most practices carry." },
        { type: 'p', text: "For a decade, the answer was to layer more reminders. A postcard. An SMS. A call from the front desk two days out. Each layer cut no-shows a few percent, but the diminishing returns kicked in fast, and the front desk drowned in reminder calls that were not the front desk's real job." },
        { type: 'p', text: "In 2026, AI receptionists are quietly closing the gap the layered approach could not reach. Practices reporting 40 % no-show reductions are not doing anything magical — they are automating three specific behaviours that were previously unaffordable at scale." },
        { type: 'h2', text: 'Why no-shows actually happen' },
        { type: 'p', text: "Ask patients why they missed an appointment and you get four answers over and over: they forgot, they had a conflict they never called in, they were afraid of the procedure, or they could not reach the office to reschedule. The first three call for reminders and empathy. The fourth calls for an office that answers the phone during working hours and off-hours." },
        { type: 'p', text: "Traditional call-back practices routinely drop 20 to 30 % of inbound patient calls to voicemail, especially during clinical hours when the front desk is chairside. Every one of those unanswered calls is a rescheduling attempt that turns into a no-show 24 to 72 hours later." },
        { type: 'h2', text: 'What the 40 % reduction looks like in practice' },
        { type: 'p', text: "The practices getting the biggest results deploy three AI behaviours in sequence. First, a personalised confirmation call 48 hours out — not an SMS, but a real voice call from the AI, in the patient's language, offering to reschedule immediately if the slot no longer works. Second, an SMS reminder 24 hours out with the exact procedure name, chair time and a one-tap reschedule link. Third, a live AI receptionist that answers 24/7 the moment a patient calls in with a conflict — and offers the next open slot from your calendar in real time." },
        { type: 'p', text: "The compounding effect is what drives the 40 %. Every conflict that would have become a no-show is caught upstream, either by the confirmation call or by the always-on receptionist. What is left — patients who had a genuine emergency — is a small residual you cannot design away." },
        { type: 'h2', text: 'What it does not replace' },
        { type: 'p', text: "AI does not replace the human relationship at the chair. It does not diagnose. It does not counsel an anxious patient. What it does replace is the front-desk workload of confirmation calls, initial triage, and after-hours coverage. Most cabinets that adopt an AI receptionist report the front desk regains 10 to 15 hours a week — hours that go into treatment plan follow-up, insurance claims, and patient onboarding, which are the tasks that actually move revenue." },
        { type: 'h2', text: 'The waitlist multiplier' },
        { type: 'p', text: "The most under-used feature in modern AI receptionists is the automated waitlist. When a patient cancels or reschedules, the AI immediately reaches out — by SMS then by voice call — to the top three candidates on a waitlist you defined. In roughly 60 % of cases, the freed slot is refilled within four hours. That is not just no-show reduction: it is same-day chair-time recovery, which turns lost revenue into full revenue on the same date." },
        { type: 'h2', text: 'Getting it live — a realistic rollout' },
        { type: 'p', text: "Practices that get the smoothest rollout follow a five-step sequence over roughly three weeks:" },
        { type: 'ul', items: [
          'Week 1: connect the AI to your PMS (Julie, Doctolib, Dentally, Curve, etc.) and load your procedure catalogue with chair times and prep instructions.',
          'Week 1: turn on the 48-hour confirmation call for a single procedure category (recall exams is the safest start).',
          'Week 2: expand to all procedure categories, activate the 24-hour SMS reminder with the reschedule link.',
          'Week 2: enable 24/7 live inbound answering for new-patient calls and rescheduling.',
          'Week 3: enable the waitlist auto-refill, then measure the no-show rate against the four weeks prior.',
        ]},
        { type: 'p', text: "Practices with clean historical data usually see the no-show rate drop the second week, then stabilise around 8 to 12 % by week six. The savings on chair time alone typically pay for the AI within the first month of use." },
        { type: 'p', text: "The dental cabinets moving fastest in 2026 are the ones treating the AI receptionist not as a call-answering tool but as an operations layer that catches every appointment friction the front desk cannot reach. The math is not marketing — it is chair time, and chair time is the practice." },
      ],
      fr: [
        { type: 'p', text: "Dans un cabinet dentaire généraliste avec deux fauteuils, une absence représente entre 150 € et 400 € de temps de fauteuil qui s'évapore. Multipliez par la moyenne du secteur — 12 à 18 % des rendez-vous en Europe, 15 à 22 % en Amérique du Nord — et la fuite annuelle atteint 80 000 à 140 000 € pour un cabinet de taille moyenne. Ce n'est pas un petit sujet. C'est la plus grosse ligne de coût silencieuse que porte la plupart des cabinets." },
        { type: 'p', text: "Pendant dix ans, la réponse a été d'empiler les rappels. Une carte postale. Un SMS. Un appel de la réception 48 h avant. Chaque couche a fait baisser les absences de quelques points, mais le rendement décroissant a vite frappé, et l'accueil s'est noyé sous des appels de confirmation qui n'étaient pas son vrai métier." },
        { type: 'p', text: "En 2026, les réceptionnistes IA comblent silencieusement l'écart que l'approche empilée n'atteignait plus. Les cabinets qui affichent 40 % de baisse d'absences ne font rien de magique — ils automatisent trois comportements précis qui étaient auparavant hors budget à cette échelle." },
        { type: 'h2', text: 'Pourquoi les patients ne viennent pas' },
        { type: 'p', text: "Quand on demande aux patients pourquoi ils ont manqué un rendez-vous, quatre réponses reviennent en boucle : j'ai oublié, j'ai eu un empêchement que je n'ai jamais signalé, j'avais peur de l'acte, ou je n'ai pas réussi à joindre le cabinet pour reprogrammer. Les trois premières se traitent par des rappels et de l'empathie. La quatrième exige un cabinet qui décroche pendant les heures d'ouverture — et en dehors." },
        { type: 'p', text: "Les cabinets traditionnels laissent 20 à 30 % des appels patients entrer en messagerie, en particulier pendant les heures cliniques quand la réception est au fauteuil. Chacun de ces appels non répondus est une tentative de reprogrammation qui devient une absence 24 à 72 heures plus tard." },
        { type: 'h2', text: "À quoi ressemble concrètement la baisse de 40 %" },
        { type: 'p', text: "Les cabinets qui obtiennent les meilleurs résultats déploient trois comportements IA en cascade. D'abord, un appel de confirmation personnalisé à J-2 — pas un SMS, un vrai appel vocal de l'IA, dans la langue du patient, avec proposition immédiate de reprogrammer si le créneau ne tient plus. Ensuite, un rappel SMS à J-1 avec le nom exact de l'acte, le temps fauteuil et un lien de reprogrammation en un clic. Enfin, une réceptionniste IA en ligne 24/7 qui décroche dès qu'un patient appelle pour signaler un empêchement — et propose le prochain créneau libre de votre agenda en temps réel." },
        { type: 'p', text: "L'effet composé fait les 40 %. Chaque empêchement qui serait devenu une absence est capté en amont, soit par l'appel de confirmation, soit par la réceptionniste toujours en ligne. Ce qui reste — les urgences authentiques — est un résidu petit que l'on ne peut pas éliminer par design." },
        { type: 'h2', text: "Ce que l'IA ne remplace pas" },
        { type: 'p', text: "L'IA ne remplace pas la relation humaine au fauteuil. Elle ne diagnostique pas. Elle ne rassure pas un patient anxieux. Ce qu'elle remplace, c'est la charge de la réception : appels de confirmation, triage initial, couverture hors heures d'ouverture. La plupart des cabinets qui adoptent une réceptionniste IA voient l'accueil récupérer 10 à 15 heures par semaine — heures reversées dans le suivi des plans de traitement, les remboursements mutuelles et l'onboarding patient, qui sont les tâches qui font réellement bouger le chiffre." },
        { type: 'h2', text: "Le multiplicateur de la liste d'attente" },
        { type: 'p', text: "La fonctionnalité la plus sous-utilisée des réceptionnistes IA modernes est la liste d'attente automatisée. Dès qu'un patient annule ou reprogramme, l'IA contacte immédiatement — par SMS puis par appel vocal — les trois premiers candidats d'une liste d'attente que vous avez définie. Dans environ 60 % des cas, le créneau libéré est repourvu en quatre heures. Ce n'est plus seulement une baisse d'absences : c'est une récupération de temps fauteuil le jour même, qui transforme un revenu perdu en revenu plein sur la même date." },
        { type: 'h2', text: "La mise en route — un déploiement réaliste" },
        { type: 'p', text: "Les cabinets qui déploient le plus proprement suivent une séquence en cinq étapes sur environ trois semaines :" },
        { type: 'ul', items: [
          "Semaine 1 : connectez l'IA à votre logiciel (Julie, Doctolib, Dentally, Curve, etc.) et chargez votre catalogue d'actes avec temps fauteuil et instructions de préparation.",
          "Semaine 1 : activez l'appel de confirmation à J-2 sur une seule catégorie d'acte (les visites de contrôle sont le démarrage le plus sûr).",
          "Semaine 2 : élargissez à toutes les catégories, activez le rappel SMS à J-1 avec le lien de reprogrammation.",
          "Semaine 2 : activez la prise d'appels entrants 24/7 pour les nouveaux patients et les reprogrammations.",
          "Semaine 3 : activez la relance automatique de la liste d'attente, puis mesurez le taux d'absence sur les quatre semaines précédentes.",
        ]},
        { type: 'p', text: "Les cabinets qui disposent d'un historique propre voient le taux d'absence baisser dès la deuxième semaine, puis se stabiliser autour de 8 à 12 % à la sixième semaine. Les économies de temps fauteuil couvrent en général le coût de l'IA dès le premier mois d'utilisation." },
        { type: 'p', text: "Les cabinets dentaires qui avancent le plus vite en 2026 sont ceux qui considèrent la réceptionniste IA non comme un outil de décroché mais comme une couche opérationnelle qui rattrape chaque friction que l'accueil ne peut plus couvrir. Les chiffres ne sont pas du marketing — c'est du temps fauteuil, et le temps fauteuil est le cabinet." },
      ],
    },
  },

  {
    slug: 'hidden-cost-missed-calls',
    title: {
      en: 'The Hidden Cost of Missed Calls for Home Service Businesses',
      fr: "Le coût caché des appels manqués pour les entreprises de services",
    },
    excerpt: {
      en: "Each missed call costs a home service business an average of 1 200 € in lost lifetime value. We break down the real numbers and show how to stop the leak.",
      fr: "Chaque appel manqué coûte en moyenne 1 200 € de valeur à vie à une entreprise de services à domicile. Voici les vrais chiffres et comment stopper la fuite.",
    },
    date: '2026-03-28',
    readTime: 7,
    tag: { en: 'Business Growth', fr: 'Croissance' },
    content: {
      en: [
        { type: 'p', text: "In the home-service economy — plumbers, electricians, HVAC, roofers, cleaners, movers, painters — the phone is not a channel. It is the channel. Depending on the trade, 60 to 85 % of new-client acquisitions still originate from an inbound call. Which means every unanswered call is not just a missed prospect. It is a hole in the top of the funnel." },
        { type: 'p', text: "The industry has under-quantified this hole for years. Owners see the calendar filling with jobs and assume they are doing well. What they do not see is the volume of calls that never made it to the calendar because nobody picked up. This article breaks down the actual numbers, then explains how the fix looks in 2026." },
        { type: 'h2', text: 'What a missed call really is' },
        { type: 'p', text: "A missed call is not just the call that rings out. Field data across home-service software platforms shows the true missed-call category has three shapes:" },
        { type: 'ul', items: [
          "The unanswered ring that goes to voicemail (roughly 55 % of misses)",
          "The hold-then-drop, where a caller is put on hold and hangs up before anyone comes back (roughly 25 %)",
          "The busy signal from a second inbound call while the first is still on the line (roughly 20 %)",
        ]},
        { type: 'p', text: "Combined, home-service businesses miss 27 % to 38 % of their inbound call volume across a full week when they rely on a human-only setup — even when that human is genuinely trying." },
        { type: 'h2', text: 'The 60-second window' },
        { type: 'p', text: "Independent studies of home-service caller behaviour agree on one hard number: when a call goes to voicemail, 60 to 75 % of callers dial the next result in Google or their list within 60 seconds. They do not leave a message. They do not call back later. They do not send an email. They pick up the phone and dial the next number." },
        { type: 'p', text: "Which means the voicemail you check at the end of the day, the callback you make an hour later, or the polite promise from your automated menu are all arriving to a client who has already booked with your competitor. Speed of pick-up is not a nice-to-have. It is the entire game." },
        { type: 'h2', text: 'The real cost per missed call' },
        { type: 'p', text: "The lifetime value of a home-service client is dominated by two things: repeat business and referrals. For a plumbing or HVAC client, average lifetime value in Belgium and France sits around 950 to 1 500 €, blending the initial job (280–400 €), follow-up jobs (roughly 1.4 per year for two years), and one referred client on average." },
        { type: 'p', text: "If your close rate on inbound calls is 45 % — a typical mid-market number — and the average lifetime value of a converted call is 1 200 €, then every missed call carries an expected value of 540 € (0.45 × 1 200). Miss ten calls a week, and you leak 5 400 € a week in expected lifetime revenue. That is 280 000 € a year." },
        { type: 'p', text: "Owners hearing this for the first time push back. Not every caller was going to convert. Not every conversion was going to reach full lifetime value. Fair. Even if you cut those numbers in half — 20 % close rate, 600 € LTV — the leak is still around 12 000 € a month, and it comes off the top. Missed-call cost is not a variable expense you decide to accept; it is a variable revenue you decide not to earn." },
        { type: 'h2', text: 'Why layering more staff does not solve it' },
        { type: 'p', text: "The instinctive response is to add front-desk headcount. It does not work. First, call volume is spiky — the mornings, lunches and after-hours peaks I described in other posts do not justify a full-time human. Second, humans miss 20 % of calls even when fully staffed: they are on another line, on lunch, in the bathroom, or triaging a client at the counter. Third, adding staff adds fixed cost that outruns the marginal revenue improvement." },
        { type: 'p', text: "This is why AI receptionists have become the default answer in 2026 for any home-service business doing more than 40 inbound calls a week. The AI answers on the first ring 24/7, in the caller's language, and captures every call at a cost that is a fraction of a single front-desk salary." },
        { type: 'h2', text: 'Stopping the leak' },
        { type: 'p', text: "The practical fix is a two-layer setup. Layer one: the AI receptionist becomes the primary pick-up on your business line — always. Layer two: when the AI detects an emergency, a high-value keyword, or an existing high-priority client, it transfers the call to your on-call human number with a briefed hand-off (name, reason, sentiment, address). This preserves the human touch where it matters and closes the leak everywhere else." },
        { type: 'p', text: "Owners who implement this correctly report inbound-call revenue capture rising 25 to 45 % in the first ninety days, without changing anything upstream in marketing or SEO. The clients were already coming. They just could not get through." },
      ],
      fr: [
        { type: 'p', text: "Dans l'économie du service à domicile — plombiers, électriciens, chauffagistes, couvreurs, nettoyeurs, déménageurs, peintres — le téléphone n'est pas un canal. C'est le canal. Selon le métier, 60 à 85 % des acquisitions de nouveaux clients passent encore par un appel entrant. Ce qui veut dire que chaque appel manqué n'est pas juste un prospect perdu. C'est un trou en haut de l'entonnoir." },
        { type: 'p', text: "Le secteur sous-quantifie ce trou depuis des années. Le patron voit son planning se remplir de jobs et suppose que tout va bien. Ce qu'il ne voit pas, c'est le volume d'appels qui n'a jamais atteint le planning parce que personne n'a décroché. Cet article pose les vrais chiffres, puis montre à quoi ressemble la solution en 2026." },
        { type: 'h2', text: "Ce qu'est réellement un appel manqué" },
        { type: 'p', text: "Un appel manqué n'est pas seulement l'appel qui sonne dans le vide. Les données terrain des plateformes de gestion de service à domicile montrent que la catégorie « appel manqué » a trois formes :" },
        { type: 'ul', items: [
          "La sonnerie sans réponse qui bascule en messagerie (environ 55 % des ratés)",
          "L'attente prolongée où l'appelant est mis en attente puis raccroche avant qu'on revienne (environ 25 %)",
          "Le signal occupé d'un second appel entrant pendant qu'un premier est en cours (environ 20 %)",
        ]},
        { type: 'p', text: "Combinés, les artisans du service à domicile manquent 27 à 38 % de leur volume d'appels entrants sur une semaine complète quand ils s'appuient sur un dispositif uniquement humain — même quand cet humain fait de son mieux." },
        { type: 'h2', text: "La fenêtre de 60 secondes" },
        { type: 'p', text: "Les études indépendantes sur le comportement des appelants convergent sur un chiffre dur : quand un appel bascule en messagerie, 60 à 75 % des appelants composent le résultat suivant de Google ou de leur liste en moins de 60 secondes. Ils ne laissent pas de message. Ils ne rappellent pas plus tard. Ils n'envoient pas de mail. Ils prennent le téléphone et appellent le numéro suivant." },
        { type: 'p', text: "Autrement dit, la messagerie que vous consultez en fin de journée, le rappel que vous passez une heure plus tard, ou la promesse polie de votre menu automatique atterrissent chez un client qui a déjà réservé chez votre concurrent. La vitesse de décroché n'est pas un confort. C'est tout le jeu." },
        { type: 'h2', text: "Le vrai coût d'un appel manqué" },
        { type: 'p', text: "La valeur à vie d'un client de service à domicile est dominée par deux choses : la récurrence et la recommandation. Pour un client plomberie ou chauffage, la valeur à vie moyenne en Belgique et en France tourne autour de 950 à 1 500 €, en mélangeant le premier job (280–400 €), les jobs suivants (environ 1,4 par an sur deux ans) et un client recommandé en moyenne." },
        { type: 'p', text: "Si votre taux de closing sur les appels entrants est de 45 % — un chiffre courant en milieu de marché — et que la valeur à vie moyenne d'un appel converti est de 1 200 €, alors chaque appel manqué porte une espérance de valeur de 540 € (0,45 × 1 200). Manquez dix appels par semaine et vous perdez 5 400 € par semaine en espérance de revenu à vie. Cela fait 280 000 € par an." },
        { type: 'p', text: "Les patrons qui entendent ça pour la première fois protestent. Tous les appelants n'auraient pas converti. Toutes les conversions n'auraient pas atteint leur pleine valeur à vie. Bien vu. Même en divisant par deux — 20 % de closing, 600 € de valeur à vie — la fuite reste autour de 12 000 € par mois, et elle part du chiffre brut. Le coût des appels manqués n'est pas une dépense variable que vous choisissez d'accepter ; c'est un revenu variable que vous choisissez de ne pas gagner." },
        { type: 'h2', text: "Pourquoi empiler du personnel ne suffit pas" },
        { type: 'p', text: "La réponse instinctive est d'ajouter de la réception. Ça ne fonctionne pas. D'abord, le volume d'appels est en pics — les pointes matin, midi et hors heures ne justifient pas un temps plein. Ensuite, les humains manquent 20 % des appels même quand ils sont pleinement mobilisés : ils sont sur une autre ligne, en pause, aux toilettes, ou en train de gérer un client au comptoir. Enfin, ajouter du personnel ajoute un coût fixe qui dépasse le gain marginal." },
        { type: 'p', text: "C'est pour cela que les réceptionnistes IA sont devenues la réponse par défaut en 2026 pour toute entreprise de service à domicile qui traite plus de 40 appels entrants par semaine. L'IA décroche à la première sonnerie 24/7, dans la langue de l'appelant, et capture chaque appel à un coût qui est une fraction d'un seul salaire de réception." },
        { type: 'h2', text: "Comment stopper la fuite" },
        { type: 'p', text: "La solution pratique se fait en deux couches. Couche 1 : la réceptionniste IA devient le décroché principal sur votre ligne pro, en permanence. Couche 2 : quand l'IA détecte une urgence, un mot-clé à forte valeur ou un client existant prioritaire, elle transfère l'appel vers votre numéro d'astreinte humain avec un passage de relais briefé (nom, motif, sentiment, adresse). Vous préservez le contact humain là où il compte et vous refermez la fuite partout ailleurs." },
        { type: 'p', text: "Les patrons qui déploient cela correctement voient la capture de revenu sur les appels entrants monter de 25 à 45 % en quatre-vingt-dix jours, sans rien changer en amont en marketing ou en SEO. Les clients venaient déjà. Ils n'arrivaient simplement pas à joindre quelqu'un." },
      ],
    },
  },

  {
    slug: 'ai-vs-human-receptionist-cost',
    title: {
      en: 'AI vs Human Receptionist: A Real Cost Comparison',
      fr: 'IA vs réceptionniste humaine : la vraie comparaison des coûts',
    },
    excerpt: {
      en: "A full-time receptionist costs 38 000 € or more per year all-in. An AI receptionist handles unlimited calls for a fraction, 24/7, with zero sick days and zero turnover. Here is the honest math.",
      fr: "Une réceptionniste temps plein coûte 38 000 € et plus par an tout compris. Une réceptionniste IA gère un volume élevé pour une fraction, 24/7, sans arrêt maladie ni turnover. Voici les calculs honnêtes.",
    },
    date: '2026-03-20',
    readTime: 8,
    tag: { en: 'Cost Analysis', fr: 'Analyse des coûts' },
    content: {
      en: [
        { type: 'p', text: "The AI-versus-human receptionist question gets asked in every SMB owner's chat in 2026. Most posts answer it lazily — a headline number, a chart, a marketing conclusion. This post does the math honestly, including the parts the AI vendors do not want to talk about, and lands on when to pick which." },
        { type: 'p', text: "The truth is more nuanced than the pitch decks. There is a clean segment where AI wins by a factor of ten, a clean segment where a human is still worth it, and a growing hybrid middle where the right answer is both." },
        { type: 'h2', text: 'The real annual cost of a human receptionist' },
        { type: 'p', text: "Owners look at the salary and stop there. That is the mistake. In Belgium in 2026, the full loaded cost of a full-time front-desk receptionist is roughly:" },
        { type: 'ul', items: [
          "Gross salary: 28 000 € to 34 000 € per year",
          "Employer social contributions: roughly 27 %, so 7 500 € to 9 200 €",
          "Meal vouchers, transport, insurances: 1 800 € to 2 600 €",
          "Training and turnover replacement (annualised over 3 years average tenure): 1 500 €",
          "Physical desk, phone system, software seat: 1 200 €",
        ]},
        { type: 'p', text: "Total: 40 000 to 48 500 € per year for a single front-desk headcount, and that headcount covers 38 hours a week — call it 1 750 hours out of 8 760 in a year, or 20 % of clock-time coverage. In France, add 3 to 6 %. In the US, expect roughly 55 000 to 68 000 USD all-in depending on the state." },
        { type: 'h2', text: 'The real annual cost of an AI receptionist' },
        { type: 'p', text: "AI receptionists in 2026 price on a subscription that scales with call volume. The realistic all-in for a small to mid-size SMB looks like this:" },
        { type: 'ul', items: [
          "Subscription tier for 800–2 500 calls per month: 1 600 to 15 000 € per year",
          "Overage above the tier: 0.15 to 0.65 € per call",
          "One-time setup (self-onboard products): 0 €. Assisted setup: 500 to 3 000 €",
          "Phone number rental: 60 to 180 € per year",
        ]},
        { type: 'p', text: "A small home-service SMB handling 400 calls a month runs around 1 800 to 4 500 € per year all-in. A mid-size dental cabinet handling 1 500 calls a month runs 6 000 to 12 000 € per year. Compared to a full-time human, the AI covers 24 hours a day 365 days a year — call it 8 760 hours out of 8 760, which is 100 % of clock-time coverage." },
        { type: 'h2', text: 'The cost-per-hour reality' },
        { type: 'p', text: "Divide the annual cost by the annual coverage hours and the picture snaps into focus. A human at 44 000 € / 1 750 hours is around 25 € per covered hour of pick-up. An AI at 3 500 € / 8 760 hours is around 0.40 € per covered hour. On a pure cost-of-coverage basis, the AI is roughly 60 times cheaper. That is not a marketing gap — that is the math." },
        { type: 'p', text: "The AI wins another way that is less obvious: it does not scale linearly. A human handling twice the calls needs a second human. An AI handling twice the calls moves to the next subscription tier, which is not double the cost — it is usually 60 to 75 % higher." },
        { type: 'h2', text: 'Where the human is still worth it' },
        { type: 'p', text: "There are three situations where a human is still the right pick. First, a very-high-touch B2B service where every inbound is a strategic account and warmth is the product (private banking, high-end consulting). Second, a walk-in reality where the front desk also greets people in the physical space (a spa, a dental cabinet with heavy walk-in). Third, a business under 15 calls a week where the AI subscription cost per call is worse than a fractional in-house resource." },
        { type: 'p', text: "Everywhere else — home services, most healthcare cabinets doing more than 400 calls a month, most retail and e-commerce phone lines, most legal and accounting practices, most beauty and wellness bookings — the AI wins on cost and often wins on quality (24/7, bilingual, structured intake, zero hold time)." },
        { type: 'h2', text: 'The hybrid model that is winning in 2026' },
        { type: 'p', text: "The most common pattern in 2026 is not either / or. It is the AI as the primary pick-up on 100 % of inbound, with human hand-offs on defined triggers: named clients, escalation keywords, complex quote requests, and any caller who explicitly asks for a human. The AI handles 80 to 90 % of volume end-to-end. The remaining 10 to 20 % lands in a human's hands with a briefed hand-off." },
        { type: 'p', text: "This hybrid model gets the coverage economics of AI, the human touch on the calls that need it, and — critically — frees the human to focus on retention, upsell and referral work rather than call-answering. The businesses that adopt this pattern typically report their existing front-desk headcount becomes more productive, not redundant." },
        { type: 'h2', text: 'Payback period' },
        { type: 'p', text: "For a home-service SMB, the AI receptionist typically pays for itself with the first two to four calls per month that would have gone to voicemail and are now booked. For a dental cabinet, it pays for itself with the first two chair-time recoveries. For a mid-size professional service firm, it pays for itself with a single retained client saved from a hold-then-drop. In every scenario we have run, the payback period is under 45 days." },
        { type: 'p', text: "The AI-versus-human question is settled on cost. The remaining question is only about fit — which model matches your operation. In 2026, for most SMBs, the answer is hybrid, with the AI as the always-on layer." },
      ],
      fr: [
        { type: 'p', text: "La question IA-contre-humain se pose dans tous les groupes de patrons de PME en 2026. La plupart des articles y répondent paresseusement — un chiffre-choc, un graphique, une conclusion marketing. Ce post fait les calculs honnêtement, y compris les parties dont les éditeurs d'IA ne veulent pas parler, et conclut sur quand choisir quoi." },
        { type: 'p', text: "La vérité est plus nuancée que les pitch decks. Il existe un segment clair où l'IA gagne par un facteur dix, un segment clair où un humain reste indispensable, et un milieu hybride grandissant où la bonne réponse est les deux." },
        { type: 'h2', text: "Le vrai coût annuel d'une réceptionniste humaine" },
        { type: 'p', text: "Les patrons regardent le salaire et s'arrêtent là. C'est l'erreur. En Belgique en 2026, le coût chargé complet d'une réceptionniste à temps plein est à peu près :" },
        { type: 'ul', items: [
          "Salaire brut : 28 000 € à 34 000 € par an",
          "Cotisations patronales : environ 27 %, soit 7 500 € à 9 200 €",
          "Chèques repas, transport, assurances : 1 800 € à 2 600 €",
          "Formation et remplacement de turnover (annualisé sur 3 ans de tenure moyenne) : 1 500 €",
          "Bureau physique, système téléphonique, licence logicielle : 1 200 €",
        ]},
        { type: 'p', text: "Total : 40 000 à 48 500 € par an pour un seul poste de réception, qui couvre 38 heures par semaine — soit 1 750 heures sur les 8 760 de l'année, ou 20 % de couverture temporelle. En France, ajoutez 3 à 6 %. Aux États-Unis, comptez 55 000 à 68 000 USD tout compris selon l'État." },
        { type: 'h2', text: "Le vrai coût annuel d'une réceptionniste IA" },
        { type: 'p', text: "Les réceptionnistes IA en 2026 tarifent en abonnement qui évolue avec le volume d'appels. Le tout compris réaliste pour une PME petite à moyenne ressemble à :" },
        { type: 'ul', items: [
          "Abonnement 800–2 500 appels par mois : 1 600 à 15 000 € par an",
          "Dépassement au-dessus du palier : 0,15 à 0,65 € par appel",
          "Setup ponctuel (produits self-serve) : 0 €. Setup assisté : 500 à 3 000 €",
          "Location de numéro : 60 à 180 € par an",
        ]},
        { type: 'p', text: "Une petite PME de service à domicile qui traite 400 appels par mois tourne entre 1 800 et 4 500 € par an tout compris. Un cabinet dentaire de taille moyenne qui traite 1 500 appels par mois tourne entre 6 000 et 12 000 € par an. Comparée à une humaine à temps plein, l'IA couvre 24 heures sur 24, 365 jours par an — soit 8 760 heures sur 8 760, ou 100 % de couverture temporelle." },
        { type: 'h2', text: "Le vrai coût par heure couverte" },
        { type: 'p', text: "Divisez le coût annuel par les heures de couverture annuelle et l'image devient nette. Une humaine à 44 000 € / 1 750 heures : environ 25 € par heure couverte de décroché. Une IA à 3 500 € / 8 760 heures : environ 0,40 € par heure couverte. Sur la seule base du coût de couverture, l'IA est environ 60 fois moins chère. Ce n'est pas un écart marketing — c'est du calcul." },
        { type: 'p', text: "L'IA gagne aussi d'une autre façon moins évidente : elle ne se cale pas linéairement. Une humaine qui traite deux fois plus d'appels demande une seconde humaine. Une IA qui traite deux fois plus d'appels passe au palier suivant, qui n'est pas le double du prix — il est en général 60 à 75 % plus élevé." },
        { type: 'h2', text: "Là où l'humain reste indispensable" },
        { type: 'p', text: "Il existe trois situations où l'humain reste le bon choix. Un service B2B à très forte valeur relationnelle où chaque appel entrant est un compte stratégique et la chaleur est le produit (banque privée, conseil haut de gamme). Une réalité de passage physique où l'accueil sert aussi les visiteurs sur place (un spa, un cabinet dentaire à fort walk-in). Une entreprise sous 15 appels par semaine où le coût d'abonnement IA par appel est pire qu'une ressource interne partielle." },
        { type: 'p', text: "Partout ailleurs — service à domicile, la plupart des cabinets de santé au-dessus de 400 appels par mois, la plupart des lignes retail et e-commerce, la plupart des cabinets juridiques et comptables, la plupart des réservations beauté et bien-être — l'IA gagne au coût et gagne souvent aussi à la qualité (24/7, bilingue, prise de brief structurée, zéro attente)." },
        { type: 'h2', text: "Le modèle hybride qui gagne en 2026" },
        { type: 'p', text: "Le schéma le plus courant en 2026 n'est pas soit / soit. C'est l'IA en décroché principal sur 100 % des appels entrants, avec passage de relais humain sur des déclencheurs définis : clients nommés, mots-clés d'escalade, demandes de devis complexes, ou tout appelant qui demande explicitement un humain. L'IA gère 80 à 90 % du volume de bout en bout. Les 10 à 20 % restants tombent chez un humain avec un passage de relais briefé." },
        { type: 'p', text: "Ce modèle hybride récupère l'économie de couverture de l'IA, le contact humain sur les appels qui l'exigent, et — surtout — libère l'humain pour se concentrer sur la rétention, l'upsell et la recommandation plutôt que sur le décroché. Les entreprises qui adoptent ce schéma constatent en général que leur effectif de réception existant devient plus productif, pas obsolète." },
        { type: 'h2', text: "Délai de retour sur investissement" },
        { type: 'p', text: "Pour une PME de service à domicile, la réceptionniste IA s'autofinance en général avec les deux à quatre premiers appels par mois qui seraient partis en messagerie et sont désormais réservés. Pour un cabinet dentaire, elle s'autofinance avec les deux premières récupérations de temps fauteuil. Pour un cabinet professionnel de taille moyenne, elle s'autofinance avec un seul client conservé après un raccroché suite à mise en attente. Dans tous les scénarios que nous avons calculés, le retour sur investissement est inférieur à 45 jours." },
        { type: 'p', text: "La question IA-contre-humain est tranchée au coût. La question restante est seulement celle de l'adéquation — quel modèle correspond à votre opération. En 2026, pour la plupart des PME, la réponse est hybride, avec l'IA en couche always-on." },
      ],
    },
  },
];

export function getArticleBySlug(slug: string): BlogArticle | undefined {
  return BLOG_ARTICLES.find((a) => a.slug === slug);
}
